### ISSUE TITLE
Use JSON.stringify instead of string concat

### ISSUE THREAD

**Issue by omelhus** [Enabler-AS/JWT-generator#16]
Hey,

`JSON.stringify` is a better way to create this string.

https://github.com/Enabler-AS/JWT-generator/blob/38de4ca90a80fbe34f435e1697506c2c348afcfb/src/components/Outputs.tsx#L31-L45

```tsx
value={JSON.stringify({
  name: data.name,
  company: data.company,
  roles: roles.map((role) => role.trim()),
  aud: data.aud
}, null, 2)}
```

**Comment by dkkazmierczak** [comment]
Hey! Thanks for the feedback, it looks really interesting. I actually fixed that output in a different way. I think there might be the problem with your solution, because if someone adds a new claim, then it's not gonna show up there, it's not dynamic. I wrote this solution instead:
```
value={`
        {     ${Object.entries(data).map(key => {
          return `
                "${key.toString().replace(/,/g, '" : "')}"`;
        })}     
                ${
                  roles.length > 0
                    ? `"roles": [ ${roles.map(role => {
                        return `
                      "${role.trim()}"`;
                      })}
                ],`
                    : ''
                }
        }`}

```
What do you think about it?
Best regards, Dominika

**Comment by omelhus** [comment]
Then how about

```tsx
  const { name, company, aud, exp, secret, ...other } = data;
  const payload = JSON.stringify(
    {
      name,
      company,
      roles: roles?.map((role) => role.trim()) ?? [],
      aud,
      exp,
      ...other,
    },
    null,
    2
  );
```

**Comment by dkkazmierczak** [comment]
Great! I modified it a little bit, but it works well. Thank you :)
